services:
  foto-splitter:
    image: ghcr.io/dernassesmart/foto-splitter:latest
    container_name: foto-splitter
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /volume1/photos/scan-eingang:/data/input
      - /volume1/photos/scan-ausgang:/data/output
      - /volume1/photos/scan-pending:/data/pending
    environment:
      - PROMINENCE=20
      - PADDING=0
      - ROTATION=0
